#ifndef ADCHPP_REASON_H_
#define ADCHPP_REASON_H_

namespace adchpp
{
	enum Reason
	{
		REASON_BAD_STATE,
		REASON_CID_CHANGE,
		REASON_CID_TAKEN,
		REASON_FLOODING,
		REASON_HUB_FULL,
		REASON_INVALID_COMMAND_TYPE,
		REASON_INVALID_IP,
		REASON_INVALID_SID,
		REASON_LOGIN_TIMEOUT,
		REASON_MAX_COMMAND_SIZE,
		REASON_NICK_INVALID,
		REASON_NICK_TAKEN,
		REASON_NO_BASE_SUPPORT,
		REASON_NO_TIGR_SUPPORT,
		REASON_PID_MISSING,
		REASON_PID_CID_LENGTH,
		REASON_PID_CID_MISMATCH,
		REASON_PID_WITHOUT_CID,
		REASON_PLUGIN,
		REASON_WRITE_OVERFLOW,
		REASON_NO_BANDWIDTH,
		REASON_INVALID_DESCRIPTION,
		REASON_WRITE_TIMEOUT,
		REASON_SOCKET_ERROR,
		REASON_HBRI,
		REASON_LAST
	};
}

#endif // ADCHPP_REASON_H_
